// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDKCiTyv1PEgtB_ETxsT5KdBgFyLCM0YU',
    appId: '1:951858479437:web:91dd425c10af42ea71f704',
    messagingSenderId: '951858479437',
    projectId: 'carmio-24f5f',
    authDomain: 'carmio-24f5f.firebaseapp.com',
    storageBucket: 'carmio-24f5f.firebasestorage.app',
    measurementId: 'G-NCHSVBHHX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmcQEkSR1aHUNyGG5hwW0on2QbMgRErs',
    appId: '1:951858479437:android:5ae24bb964be3c1571f704',
    messagingSenderId: '951858479437',
    projectId: 'carmio-24f5f',
    storageBucket: 'carmio-24f5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkGwYEylkeD6BBfA95t3umryW1w3-MgBo',
    appId: '1:951858479437:ios:d9c2c2e201b3b51a71f704',
    messagingSenderId: '951858479437',
    projectId: 'carmio-24f5f',
    storageBucket: 'carmio-24f5f.firebasestorage.app',
    iosBundleId: 'com.example.drivers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkGwYEylkeD6BBfA95t3umryW1w3-MgBo',
    appId: '1:951858479437:ios:d9c2c2e201b3b51a71f704',
    messagingSenderId: '951858479437',
    projectId: 'carmio-24f5f',
    storageBucket: 'carmio-24f5f.firebasestorage.app',
    iosBundleId: 'com.example.drivers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDKCiTyv1PEgtB_ETxsT5KdBgFyLCM0YU',
    appId: '1:951858479437:web:1c58d02eb1f649da71f704',
    messagingSenderId: '951858479437',
    projectId: 'carmio-24f5f',
    authDomain: 'carmio-24f5f.firebaseapp.com',
    storageBucket: 'carmio-24f5f.firebasestorage.app',
    measurementId: 'G-6FT4QK4541',
  );
}
